locale: "en-US"
title: fals.io # Title of your site
url: "https://fals.github.io" # the base hostname & protocol for your site
baseurl: "https://fals.github.io" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Filipe Lima
  email: fals.xp@gmail.com
  twitter: fals_xp

# Social details for the jekyll-seo-tag gem
social:
  name: fals.io
  links:
    - https://www.linkedin.com/in/filipe-augusto-lima-de-souza-95a16833
    - https://github.com/fals
    - https://stackoverflow.com/users/2072198/fals

permalink: pretty

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
